$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  transports: [console, file]
  level: debug
  show_progress: true
  path_settings:
    path_pattern: "logs/mcp-agent-{unique_id}.jsonl"
    unique_id: "timestamp" # Options: "timestamp" or "session_id"
    timestamp_format: "%Y%m%d_%H%M%S"

mcp:
  servers:
    smithery-github:
      name: "@smithery/github"
      description: "github server"
      transport: "websocket"
      # This URL needs to be constructed on Smithery. Smithery requires server json configSchema
      # object to be passed in as base64. See details here:
      # https://smithery.ai/docs/registry#connecting-to-websocket-servers
      # url: "wss://server.smithery.ai/@smithery-ai/github/ws?config=<enter your base64 encoded configSchema object>"

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  #  default_model: "o3-mini"
  default_model: "gpt-4o-mini"
