"""Apply diffs generated by the implementer."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass
class ApplyResult:
    written_files: list[Path]


def apply_diff(base_dir: str | Path, diff: str, target_files: Iterable[str]) -> ApplyResult:
    base = Path(base_dir)
    base.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for rel in target_files:
        path = base / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(diff)
        written.append(path)
    return ApplyResult(written_files=written)


__all__ = ["apply_diff", "ApplyResult"]
