$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  transports: [console]
  level: debug

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
      description: "Fetch content at URLs from the world wide web"
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem"]
      description: "Read and write files on the filesystem"

openai:
  default_model: gpt-4o
  # Secrets are loaded from mcp_agent.secrets.yaml
