# 🧠 Brand & Content Template

---

## 🏢 Company Snapshot

**Name**: [Your Company Name]  
**Industry**: [e.g., AI, SaaS, HealthTech, Fintech]  

**Target Audience**:
- [Audience #1]  
- [Audience #2]  
- [Audience #3]  
- [Audience #4]  
- [Audience #5]  

---

## 🗣️ Brand Voice & Personality

**Personality**  
[Describe your brand voice in 1–2 sentences — e.g., Bold but helpful, technical but clear]

**Tone Keywords**  
- [Keyword 1]  
- [Keyword 2]  
- [Keyword 3]  
- [Keyword 4]  
- [Keyword 5]  

**Avoid**  
- [What kind of tone/language to stay away from — e.g., sales-heavy, robotic, vague buzzwords]  

---

## 📣 Messaging Pillars

1. [Messaging Pillar #1]  
2. [Messaging Pillar #2]  
3. [Messaging Pillar #3]  
4. [Optional Pillar #4]  
5. [Optional Pillar #5]  

---

## 🧭 Content Platform Guidelines

### ✅ LinkedIn
- **Max Word Count**: [e.g., 100–200]  
- **Tone**: [e.g., Professional but conversational]  
- **Guideline**: [e.g., Be human. Avoid startup buzz. Focus on impact.]

### ✅ Twitter
- **Max Word Count**: [e.g., 50–100]  
- **Tone**: [e.g., Sharp, witty, to-the-point]  
- **Guideline**: [e.g., Write like you're texting a peer. Start with a punchline.]

### ✅ Email
- **Max Word Count**: [e.g., 300–500]  
- **Tone**: [e.g., Friendly, clear, no-nonsense]  
- **Guideline**: [e.g., Use plain English. Add a helpful CTA.]

---

## 📏 Quality Standards

### What Great Looks Like
- Sounds human, not robotic  
- Specific names, dates, numbers, or examples  
- Zero filler or fluff  
- Matches brand personality and tone  
- Actionable or insightful content  

### What to Avoid
- Generic or overused marketing phrases  
- Vague descriptions  
- Corporate filler, AI-sounding sentences  

### ❌ Banned Phrases (Edit based on your brand)
- "Unlock potential"  
- "Revolutionary"  
- "Excited to announce"  
- "Game-changing"  
- "Scale effortlessly"  
- "Don’t miss out"  

---

## 🧪 Prompt Instructions for AI Writers or Content Creators

> **Instruction**: Create authentic, engaging content that reflects the brand’s tone and values. Pull from content samples when available. Be clear, natural, and useful.

### ✅ Good Examples
- "[Insert strong example — e.g., 'We shipped X and it’s now powering Y']"  
- "[Insert short post — e.g., '500 devs signed up in 48 hours. Here's what we learned.']"  

### ❌ Bad Examples
- "[Overly hypey line — e.g., 'Are YOU ready to transform the future of tech?']"  
- "[Buzzword salad — e.g., 'Unleashing the potential of synergistic innovation.']"  