name: Create Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
      message:
        description: 'Tag message'
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create tag
        env:
          TAG_NAME: ${{ github.event.inputs.tag }}
          TAG_MESSAGE: ${{ github.event.inputs.message }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "$TAG_NAME" -m "$TAG_MESSAGE"
          git push origin "$TAG_NAME"
